name: ci
run-name: CI for ${{ github.sha }} on ${{ github.ref_name }}

on:
   workflow_dispatch:
   push:
     branches:
     - "main"
     - "release-**"
     - "track/**"
     paths-ignore:
     - "terraform/**"
   pull_request:
     branches:
     - "*"
     paths-ignore:
     - "terraform/**"

jobs:
  tests:
    name: CI
    # uses: canonical/identity-team/.github/workflows/charm-pull-request.yaml@IAM-1424-ck8s-operator-action
    uses: canonical/identity-team/.github/workflows/charm-pull-request.yaml@IAM-1424-use-canonical-k8s
    with:
      container-name: "kratos"
      use-charmcraftcache: true
      node-size: large
      # use-canonical-k8s: true
